### ISSUE TITLE
allow specifiying a data whitelist to reduce the data transferred

### ISSUE THREAD

**Issue by Summertime** [pushshift/reddit_sse_stream#10]
e.g.

`http://stream.pushshift.io/?subreddit=news&data_keys=name,title,url,body,created_utc,author`

which would do something like:

```python
data = comment['json']
if 'data_keys' in params:
    data_keys = params['data_keys'].split(',')
    json = json.loads(data)
    data = json.dumps({k:v for k,v in json.items() if k in data_keys})
```
and likewise for submissions

more processing on the server, but far less data sent?

**Comment by pushshift** [comment]
I went ahead and basically used your code verbatim.  Nicely done.

Thanks!

**Comment by Summertime** [comment]
seems to work pretty good!

if CPU usage does ever become a problem, could trim it down a couple of ways for the filtering at least:

```python
# Two lookups per filtered, should be cheaper in majority of cases
data = json.dumps({k:j[k] for k in filtered_keys if k in j})

# One lookup, but the syntax won't arrive until 3.8 (late 2019)
# if the PEP is successful https://www.python.org/dev/peps/pep-0572/
# We use ... as a sentinel as the other singletons
# (None, True, False) are valid json results
data = json.dumps({k:v for k in filtered_keys if (v := j.get(k, ...)) is not ...})
```

**Comment by pushshift** [comment]
@Summertime -- Yeah, there are several places where the code could be optimized.  Generally when I code, my first pass attempt is to just get it working.  In time, I will refactor the parts of the code that reward the greatest speed increase benefits.  

The CPU usage right now is very low.  CPU's are just so powerful today that even unoptimized code can work well for quite some time.

Thank you for all your suggestions!  Eventually I will do a second pass on the code and make those optimizations you highlighted.
